version: '2.1'
orbs:
  cypress: cypress-io/cypress@6

jobs:
  cypress-run-with-report:
    executor: cypress/default
    steps:
      - cypress/install:
          install-browsers: true
      - cypress/run-tests:
          cypress-command: npx cypress run --browser chrome
      - store_artifacts:
          path: cypress/reports

workflows:
  use-my-orb:
    jobs:
      - cypress-run-with-report
